platform :ios, '11.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/NextUserSF/NextUserPodSpecs.git'


target 'NextUserLibraryDemo' do
    pod 'NextUser', :path => '/Users/adrian/Dev/NextUser/mobile-sdk-ios'
    pod 'Firebase/Core'
    pod 'Firebase/Messaging'
end
