platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/NextUserSF/NextUserPodSpecs.git'


target 'NextUserLibraryDemo' do
    pod 'KontaktSDK', '~> 1.0'
    pod 'NextUser', :path => '/Users/adrian/Dev/NextUser/mobile-sdk-ios'
end
